name       : kauth
version    : 5.28.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.28/kauth-5.28.0.tar.xz : 80b8f7a7038cfbe12deb18d040a1e6d1ae19f3d6b01a35572b874f3f6f6ca726
license    : LGPL-2.1
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel:
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-stateless-configuration.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
