name       : kauth
version    : 5.63.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/kauth-5.63.0.tar.xz : 2c4917f0bb49f09b232aeda9d3282eef0e235124fab1dab0deeae2ae7a7df321
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
