name       : kauth
version    : 5.50.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/kauth-5.50.0.tar.xz : f7ecff8ee7f06372275f651e9a6f26c68efa0b0d9696ea33f1272173143af396
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-stateless-configuration.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
