name       : kauth
version    : 5.89.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.89/kauth-5.89.0.tar.xz : df9a81af5b0754d528799ec944de02c1b22c4a4b97d9e3dc0132232d4fee49fb
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
optimize   : lto
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
