name       : kauth
version    : 5.67.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kauth-5.67.0.tar.xz : 4f4a0323adcfdc6f80c38c289a73a3b7af6bf5141acd80712eb669b6ffb8bcc3
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
