name       : kauth
version    : 5.53.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kauth-5.53.0.tar.xz : 6b7c270812268e1a6925011932d8f8242635775f610377582e991b86ec578130
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-stateless-configuration.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
