name       : kauth
version    : 5.62.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/kauth-5.62.0.tar.xz : 31162621200df4b927719e34ce62004c51e79b9d785f9c3056c6902f80eeefe6
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
