name       : kauth
version    : 5.80.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/kauth-5.80.0.tar.xz : 26f07de07729abf90500749d7746eee63398fe96ca00d32f845084b4c89896dd
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
optimize   : lto
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
