name       : kauth
version    : 5.25.0
release    : 2
source     :
    - http://download.kde.org/stable/frameworks/5.25/kauth-5.25.0.tar.xz : 1d62b32d88ba6c1e71e7b3ef67366710b9ce4488bcf82280fbe70d79b52f963a
license    : LGPL-2.1
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel:
        - kcoreaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
