name       : kauth
version    : 5.93.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/kauth-5.93.0.tar.xz : 34580078bfdf631835f3ac52955f2149209908b935a7cfec6fe5b4956c3ada6c
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
optimize   : lto
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
