name       : kauth
version    : 5.41.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/kauth-5.41.0.tar.xz : 548cc6eeb13edf3d3cda94700fe0031cdab3ce5b2d2f47e1e48cf77107726ac2
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-stateless-configuration.patch
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
