name       : kauth
version    : 5.64.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kauth-5.64.0.tar.xz : ac95525bf1430868c8f54dbdc986478cf7b21192ad3b486381485b429eadddcc
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
