name       : kauth
version    : 5.60.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kauth-5.60.0.tar.xz : 50a2a2eb90d7529bb6fc4ddd77e37ef5b25c612b18487cc63d8d086d5ec28916
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
