name       : kauth
version    : 5.66.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/kauth-5.66.0.tar.xz : f167ec8f926caf348a161a39e0c0588f517fe3a49ab4f39c1dfa94f47e104414
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
