name       : kauth
version    : 5.92.0
release    : 66
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/kauth-5.92.0.tar.xz : 44824bf68ee510d8aa0189a9d4b44568b0fe20d17ba45e3b739db1927bfa4728
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
optimize   : lto
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
