name       : kauth
version    : 5.109.0
release    : 76
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/kauth-5.109.0.tar.xz : 3f7d81fccbc9336306a88ae52016cde3645b3bf9fed16ac3d17fc6ef85d7a0ae
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
optimize   : lto
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
