name       : kauth
version    : 5.59.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kauth-5.59.0.tar.xz : e7d9cbbc108df1c2d41038785967ed9a9489987462ba5f1f1a9d270ae9e1093c
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
