name       : kauth
version    : 5.32.0
release    : 4
source     :
    - http://download.kde.org/stable/frameworks/5.32/kauth-5.32.0.tar.xz : b8326b4ca3a43169f70c08186bd1230777c1caa5857e7e5770d6f0644dc06d02
license    : LGPL-2.1
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-stateless-configuration.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
