name       : kauth
version    : 5.47.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/kauth-5.47.0.tar.xz : 29c7c3d6c539d52200806502e4b11a132c1941512df6f2d3e073ed3e7f7e00e9
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %patch -p1 < $pkgfiles/0001-Enable-stateless-configuration.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
