name       : kauth
version    : 5.35.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.35/kauth-5.35.0.tar.xz : a66bf2c350a8004313fb37bbfb4799cc2e33c152dbf79b53d1b020c04b5175b9
license    : LGPL-2.1
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-stateless-configuration.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
