name       : kauth
version    : 5.39.0
release    : 10
source     :
    - https://download.kde.org/stable/frameworks/5.39/kauth-5.39.0.tar.xz : b184b817d155b272cf42fa748c6d3c9f1713be423551d2a74e297821f6ee7221
license    : LGPL-2.1
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-stateless-configuration.patch
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
