name       : kauth
version    : 5.48.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/kauth-5.48.0.tar.xz : 47afa9e89543be8bd732fc8b8c0b6e04b71d36e55c547697623ed546845eb702
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %patch -p1 < $pkgfiles/0001-Enable-stateless-configuration.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
