name       : kauth
version    : 5.94.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.94/kauth-5.94.0.tar.xz : 9cfed0ad69a8fa5df88273a5ef340d7b6dff1cd3e9d53bda16f3cf4afdd64159
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
optimize   : lto
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
