name       : kauth
version    : 5.69.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/kauth-5.69.0.tar.xz : 20cff8f232ac648bbdad824d819786190ccab2eef2e285866952d63e3edf1ec2
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
