name       : kauth
version    : 5.90.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.90/kauth-5.90.0.tar.xz : 23a45f68062432b65f4264f371e7f1753034dba3a86d5e44bf9fb1abf30d91bc
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
optimize   : lto
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
