name       : kauth
version    : 5.77.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/kauth-5.77.0.tar.xz : b5a54ec41b1be0a72d710c43b8e00a7e3ac5e982c73da8ae48edf16cbc7c8c1e
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
