name       : kauth
version    : 5.74.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kauth-5.74.0.tar.xz : e0aa6206c4bf9220d1c4882b8b77f9cf9202646b64b8a249a60a9d4b272e3bfc
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
