name       : kauth
version    : 5.51.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kauth-5.51.0.tar.xz : 15faa8e4152b46a5833256ca6d39d22509487aa61853ee5d74c93e3869b2f95d
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-stateless-configuration.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
