name       : kauth
version    : 5.42.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/kauth-5.42.0.tar.xz : 91ebf3554551c3815e89e53e577e42d7cc3ac1f4966215fbbc93a60ca1587812
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(polkit-qt5-1)
    - extra-cmake-modules
    - kcoreaddons-devel
rundeps    :
    - devel :
        - kcoreaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-stateless-configuration.patch
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
